### ISSUE TITLE
breaking

### ISSUE THREAD

**Issue by fernstedt** [musana/mx-takeover#13]
[*] 7175 domain will be scanned.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x73cafb]

goroutine 24 [running]:
main.parseMXDomain({0xc0001b9728, 0x13}, {0xc0003b6a10?, 0x1, 0x1?})
        /root/go/pkg/mod/github.com/musana/mx-takeover@v0.1.1/mx-takeover.go:207 +0x9b
main.getDNSRecord(0x407b78?, {0xc0001b9728, 0x13}, 0x1?)
        /root/go/pkg/mod/github.com/musana/mx-takeover@v0.1.1/mx-takeover.go:172 +0x6d6
main.main.func1()
        /root/go/pkg/mod/github.com/musana/mx-takeover@v0.1.1/mx-takeover.go:93 +0x2f
github.com/gammazero/workerpool.worker(0xc0001001e0?)
        /root/go/pkg/mod/github.com/gammazero/workerpool@v1.1.2/workerpool.go:243 +0x29
created by github.com/gammazero/workerpool.startWorker
        /root/go/pkg/mod/github.com/gammazero/workerpool@v1.1.2/workerpool.go:234 +0x65

**Comment by musana** [comment]
The domain names that you provide to the tool should start with http:// or https://
